survey <- data.frame(id = 1:50,
                     gender = sample(c("M","F"), size =50, replace = TRUE),
                     age    = sample(c(18:65), size = 50, replace = TRUE),
                     agree1 = sample(agree_scale(), size = 50, replace = TRUE),
                     agree2 = sample(c(agree_scale(),NA), size = 50, replace = TRUE),
                     agree3 = sample(agree_scale(), size = 50, replace = TRUE),
                     often1 = sample(often_scale(), size = 50, replace = TRUE),
                     often2 = sample(often_scale(), size = 50, replace = TRUE),
                     open1  = stringi::stri_rand_lipsum(50),
                     open2  = stringi::stri_rand_lipsum(50),
                     other = sample(c(agree_scale(), LETTERS[1:2]),size = 50, replace = TRUE),
                     multi = replicate(50, paste(sample(c("US","UK","CAN","MEX"), size = sample(0:3, size = 1), replace = FALSE), collapse = ";")),
                     factor = sample(paste0("opt", 1:5), size = 50, replace = TRUE),
                     stringsAsFactors = FALSE)

schema <- data.frame(q_num = 1:length(survey),
                     q_varname = names(survey),
                     q_type = c("meta", "factor", "num", rep("ordered", 5), rep("open", 2), "other_factor", "multi", "factor"),
                     q_group = c("One", "Two", "Three", rep("Four", 3), "Five", "Five", "Six", "Six", "Seven", "Eight", "Nine"),
                     q_description = c("Identification #",
                                       "What is your gender?",
                                       "What is your Age?",
                                       "To what extent do you agree with the following statements?",
                                       "To what extent do you agree with the following statements?",
                                       "To what extent do you agree with the following statements?",
                                       "How often do you do each of the following?",
                                       "How often do you do each of the following?",
                                       "Tell me how you feel?",
                                       "What do you think?",
                                       "Select an option or write in something else",
                                       "Choose all that apply.",
                                       "Choose One"),
                     q_detail = c("Identification #",
                                       "What is your gender?",
                                       "What is your Age?",
                                       "Cheese is good.",
                                       "Bananas are bad.",
                                       "Apples are dumb.",
                                       "Eat pizza over the sink like a rat.",
                                       "Cry.",
                                       "Tell me how you feel?",
                                       "What do you think?",
                                       "Select an option or write in something else",
                                       "Choose all that apply.",
                                        "Choose One"),
                     stringsAsFactors = FALSE)

# write.csv(survey, "data/sample/sample_survey.csv", row.names = FALSE)
# write.csv(schema, "data/sample/sample_schema.csv", row.names = FALSE)